version: 2
jobs:
  deploy:
    docker:
      - image: olizilla/ipfs-dns-deploy:1.2
        environment:
          SUBDOMAIN: xkcd.hacdias.com
          DOMAIN: hacdias.com
          BUILD_DIR: output
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Install jq
          command: sudo apt install jq
      - restore_cache:
          keys:
            - xkcd-v1
      - run:
          name: Fetch latest version of archive
          command: npx xkcd-clone -d $BUILD_DIR
      - save_cache:
          key: xkcd-v1
          paths:
            - output # Must be equal to BUILD_DIR
      - run:
          name: Pin website, post notification for PRs or update DNS on master
          no_output_timeout: 60m
          command: |
            pin_name="$SUBDOMAIN build $CIRCLE_BUILD_NUMBER"

            ipfs-cluster-ctl --host /dnsaddr/cluster.ipfs.io \
              --basic-auth $CLUSTER_USER:$CLUSTER_PASSWORD \
              add -r $BUILD_DIR | tee out.txt

            hash=$(cat out.txt | tail -1 | sed 's/added//' | sed "s/$BUILD_DIR//" | xargs)

            echo "Website added to IPFS: https://ipfs.io/ipfs/$hash"

            if [ "$CIRCLE_BRANCH" == "master" ] ; then
              curl -X POST \
                -H "Content-Type: application/json" \
                -H "pinata_api_key: $PINATA_API" \
                -H "pinata_secret_api_key: $PINATA_SECRET" \
                -d "{\"hashToPin\":\"$hash\"}" \
                https://api.pinata.cloud/pinning/addHashToPinQueue

              npx dnslink-cloudflare -d $DOMAIN -r _dnslink.xkcd -l /ipfs/$hash
            fi
workflows:
  version: 2
  update:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - deploy:
          context: IPFS Pinning
  deploy:
    jobs:
      - deploy:
          context: IPFS Pinning
